# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: gabischima
email: gabismauricio@gmail.com
tagline: Personal site from Gabriela Schirmer Mauricio, brazilian developer, designer and illustrator.
description: >- # this means to ignore newlines until "baseurl:"
  Personal site from Gabriela Schirmer Mauricio, brazilian developer, designer and illustrator.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabischima.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gabischima
github_username:  gabischima
exclude:
  - Makefile
  - dist
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock

version: '0.5.1'

seo:
  pt:
    description:
      Portfolio de Gabriela Schirmer Mauricio. Desenvolvedora, designer e ilustradora.
  en:
    description: >- # this means to ignore newlines until "baseurl:"
      Personal site from Gabriela Schirmer Mauricio, brazilian developer, designer and illustrator.

sass:
  style: compressed

menu:
  en:
    about:
      title: about
      link: /en/
    portfolio:
      title: portfolio
      link: /en/portfolio
    curriculum:
      title: curriculum
      link: /en/curriculum
    ennecoisa:
      title: ennecoisa
      link: /en/ennecoisa
    contact:
      title: contact
      link: /en/contact
  pt:
    about:
      title: sobre
      link: /pt/
    portfolio:
      title: portfolio
      link: /pt/portfolio
    curriculum:
      title: currículo
      link: /pt/curriculo
    ennecoisa:
      title: ennecoisa
      link: /pt/ennecoisa
    contact:
      title: contato
      link: /pt/contato

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  social_medias:
    output: false
  curriculum:
    output: false
  portfolio:
    output: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
