# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: gabischima
email: gabismauricio@gmail.com
tagline: Personal site from Gabriela Schirmer Mauricio, brazilian developer, designer and illustrator.
description: >-
  Personal site from Gabriela Schirmer Mauricio, brazilian developer, designer and illustrator.
baseurl: ""
url: "https://gabischima.github.io"
twitter_username: gabischima
github_username:  gabischima

version: '1.2.0'

seo:
  pt:
    description:
      Portfolio de Gabriela Schirmer Mauricio. Desenvolvedora, designer e ilustradora.
  en:
    description: >- # this means to ignore newlines until "baseurl:"
      Gabriela Schirmer Mauricio personal site. Brazilian developer, designer and illustrator.

sass:
  style: compressed

menu:
  en:
    home:
      title: home
      link: /en/
    portfolio:
      title: portfolio
      link: /en/portfolio
    curriculum:
      title: curriculum
      link: /en/curriculum
    ennecoisa:
      title: ennecoisa
      link: /en/ennecoisa
  pt:
    home:
      title: home
      link: /pt/
    portfolio:
      title: portfolio
      link: /pt/portfolio
    curriculum:
      title: currículo
      link: /pt/curriculum
    ennecoisa:
      title: ennecoisa
      link: /pt/ennecoisa

cookies:
  pt:
    text: Esse site utiliza cookies para analytics e preservar configurações de ambiente (modo dark ou light). Nenhum dado pessoal ou identificável está sendo coletado.
    agree: aceito
  en:
    text: This site uses cookies for analytics and save environment (light/dark) settings. No personal or personally identifiable data is being tracked.
    agree: I agree

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  social_medias:
    output: false
  curriculum:
    output: false
  portfolio:
    output: false


portfolioTabbar:
  all:
    pt:
      name: "todos"
      url: ""
    en:
      name: "all"
      url: ""
  development:
    pt:
      name: "desenvolvimento"
      url: "/development"
    en:
      name: "development"
      url: "/development"
  design:
    pt:
      name: "design"
      url: "/design"
    en:
      name: "design"
      url: "/design"
  illustration:
    pt:
      name: "ilustração"
      url: "/illustration"
    en:
      name: "illustration"
      url: "/illustration"

exclude:
  - Makefile
  - dist
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - create-post.sh
